/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ArtifactProposals": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CostTracking": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EmailArtifacts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EmailMessages": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EmailParser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EmailRuns": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EmailStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Mailboxes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OutcomeLinks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PrivacyOptIn": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RoutingRules": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}