module.exports = {
  sources: ['.env', '.env.local'],
  rootExampleFile: '.env.example',
  variables: [
    {
      key: 'API_KEY_HASH_SECRET',
      description: 'Shared secret used to hash backend API keys.',
      example: 'replace-with-long-random-secret',
      secret: true,
    },
    {
      key: 'APP_BASE_PATH',
      aliases: ['NEXT_PUBLIC_APP_BASE_PATH'],
      description: 'Base path for the main application routes.',
      example: '/app',
    },
    {
      key: 'APP_VERSION',
      aliases: ['NEXT_PUBLIC_APP_VERSION'],
      description: 'Version label exposed by the landing app UI.',
      example: '1.3.20',
    },
    {
      key: 'AWS_ACCOUNT_ID',
      description: 'AWS account id used by backend and infra tooling.',
      example: '058264267235',
    },
    {
      key: 'AWS_REGION',
      description: 'Primary AWS region for TLAO services.',
      example: 'us-east-2',
    },
    {
      key: 'BACKEND_API_KEY',
      description: 'API key used by the email package when calling the backend.',
      example: 'replace-with-backend-api-key',
      secret: true,
    },
    {
      key: 'BACKEND_API_URL',
      description: 'Backend base URL used by the email package.',
      example: 'http://localhost:3000',
    },
    {
      key: 'BEDROCK_MAX_TOKENS',
      description: 'Default Bedrock max tokens for backend requests.',
      example: '2000',
    },
    {
      key: 'BEDROCK_MODEL_ID',
      description: 'Default Bedrock model id for backend requests.',
      example: 'anthropic.claude-3-sonnet-20240229-v1:0',
    },
    {
      key: 'BEDROCK_TEMPERATURE',
      description: 'Default Bedrock temperature for backend requests.',
      example: '0.7',
    },
    {
      key: 'CODESTAR_CONNECTION_ARN',
      description: 'CodeStar connection ARN used when creating infra pipelines.',
      example: 'arn:aws:codestar-connections:us-east-2:058264267235:connection/replace-me',
    },
    {
      key: 'DOCS_BASE_URL',
      aliases: ['BASE_URL'],
      description: 'Base URL used by the docs site itself.',
      example: '/',
    },
    {
      key: 'DOCS_PUBLIC_BASE_PATH',
      aliases: ['NEXT_PUBLIC_DOCS_BASE_PATH'],
      description: 'Docs path exposed to the landing app for cross-app links.',
      example: '/documentation',
    },
    {
      key: 'DOCS_SITE_URL',
      aliases: ['SITE_URL'],
      description: 'Production site URL used by the docs app.',
      example: 'https://docs.tlao.com',
    },
    {
      key: 'DYNAMODB_DOCUMENTS_TABLE',
      description: 'Backend DynamoDB table for documents.',
      example: 'tlao-documents',
    },
    {
      key: 'DYNAMODB_RESULTS_TABLE',
      description: 'Backend DynamoDB table for results.',
      example: 'tlao-results',
    },
    {
      key: 'DYNAMODB_SESSIONS_TABLE',
      description: 'Backend DynamoDB table for sessions.',
      example: 'tlao-sessions',
    },
    {
      key: 'DYNAMODB_USERS_TABLE',
      description: 'Backend DynamoDB table for users.',
      example: 'tlao-users',
    },
    {
      key: 'EMAIL_BUCKET',
      description: 'S3 bucket used by the email package.',
      example: 'tlao-email',
    },
    {
      key: 'FREE_TIER_DAILY_LIMIT',
      description: 'Backend free-tier daily request limit.',
      example: '1000',
    },
    {
      key: 'FREE_TIER_RATE_LIMIT',
      description: 'Backend free-tier per-minute request limit.',
      example: '100',
    },
    {
      key: 'FREE_TIER_STORAGE_CAP',
      description: 'Backend free-tier storage cap in bytes.',
      example: '5368709120',
    },
    {
      key: 'FREE_TIER_TOKEN_LIMIT',
      description: 'Backend free-tier daily token limit.',
      example: '100000',
    },
    {
      key: 'GITHUB_REPO',
      description: 'GitHub repository slug used by infra pipeline config.',
      example: 'tlao-org/tlao',
    },
    {
      key: 'INFRA_CREATE_PIPELINES',
      description: 'Safety gate for creating or mutating CodePipeline resources.',
      example: 'false',
    },
    {
      key: 'LANDING_BASE_PATH',
      aliases: ['NEXT_PUBLIC_BASE_PATH', 'NEXT_PUBLIC_LANDING_BASE_PATH'],
      description: 'Base path used by the landing app.',
      example: '',
    },
    {
      key: 'LOG_LEVEL',
      description: 'Default backend log level.',
      example: 'info',
    },
    {
      key: 'S3_BUCKET_NAME',
      description: 'S3 bucket used by the backend package.',
      example: 'tlao-documents',
    },
    {
      key: 'STALWART_API_KEY',
      description:
        'Legacy Stalwart auth value. Use username:secret for Basic auth or a raw bearer token if required.',
      example: 'tlao-provisioner:replace-with-stalwart-api-secret',
      secret: true,
    },
    {
      key: 'STALWART_API_USERNAME',
      description: 'Stalwart management API username or API key id used for mailbox provisioning.',
      example: 'tlao-provisioner',
    },
    {
      key: 'STALWART_API_SECRET',
      description: 'Stalwart management API secret used for mailbox provisioning.',
      example: 'replace-with-stalwart-api-secret',
      secret: true,
    },
    {
      key: 'STALWART_URL',
      description: 'Base URL for the local or remote Stalwart server.',
      example: 'http://localhost:8080',
    },
  ],
  targets: [
    {
      id: 'backend',
      outputFile: 'packages/backend/.env',
      exampleFile: 'packages/backend/.env.example',
      entries: [
        { source: 'API_KEY_HASH_SECRET', required: true },
        { source: 'AWS_ACCOUNT_ID' },
        { source: 'AWS_REGION', required: true },
        { source: 'AWS_REGION', target: 'S3_REGION', required: true },
        { source: 'BEDROCK_MAX_TOKENS' },
        { source: 'BEDROCK_MODEL_ID', required: true },
        { source: 'BEDROCK_TEMPERATURE' },
        { source: 'DYNAMODB_DOCUMENTS_TABLE', required: true },
        { source: 'DYNAMODB_RESULTS_TABLE', required: true },
        { source: 'DYNAMODB_SESSIONS_TABLE', required: true },
        { source: 'DYNAMODB_USERS_TABLE', required: true },
        { source: 'FREE_TIER_DAILY_LIMIT' },
        { source: 'FREE_TIER_RATE_LIMIT' },
        { source: 'FREE_TIER_STORAGE_CAP' },
        { source: 'FREE_TIER_TOKEN_LIMIT' },
        { source: 'LOG_LEVEL' },
        { source: 'S3_BUCKET_NAME', required: true },
      ],
    },
    {
      id: 'docs',
      outputFile: 'apps/docs/.env.local',
      exampleFile: 'apps/docs/.env.example',
      entries: [
        { source: 'DOCS_BASE_URL', target: 'BASE_URL', required: true },
        { source: 'DOCS_SITE_URL', target: 'SITE_URL', required: true },
      ],
    },
    {
      id: 'email',
      outputFile: 'packages/email/.env',
      exampleFile: 'packages/email/.env.example',
      entries: [
        { source: 'AWS_REGION', required: true },
        { source: 'AWS_REGION', target: 'BEDROCK_REGION', required: true },
        { source: 'BACKEND_API_KEY', required: true },
        { source: 'BACKEND_API_URL', required: true },
        { source: 'EMAIL_BUCKET', required: true },
        { source: 'STALWART_API_KEY' },
        { source: 'STALWART_API_USERNAME', required: true },
        { source: 'STALWART_API_SECRET', required: true },
        { source: 'STALWART_URL', required: true },
      ],
    },
    {
      id: 'infra',
      outputFile: 'packages/infra/.env',
      exampleFile: 'packages/infra/.env.example',
      entries: [
        { source: 'AWS_ACCOUNT_ID', required: true },
        { source: 'AWS_REGION', required: true },
        { source: 'CODESTAR_CONNECTION_ARN', required: true },
        { source: 'GITHUB_REPO', required: true },
        { source: 'INFRA_CREATE_PIPELINES' },
      ],
    },
    {
      id: 'landing',
      outputFile: 'apps/landing/.env.local',
      exampleFile: 'apps/landing/.env.example',
      entries: [
        { source: 'APP_BASE_PATH', target: 'NEXT_PUBLIC_APP_BASE_PATH', required: true },
        { source: 'APP_VERSION', target: 'NEXT_PUBLIC_APP_VERSION' },
        { source: 'DOCS_PUBLIC_BASE_PATH', target: 'NEXT_PUBLIC_DOCS_BASE_PATH', required: true },
        { source: 'LANDING_BASE_PATH', target: 'NEXT_PUBLIC_BASE_PATH' },
        { source: 'LANDING_BASE_PATH', target: 'NEXT_PUBLIC_LANDING_BASE_PATH', required: true },
      ],
    },
  ],
}
