AWSTemplateFormatVersion: '2010-09-09'
Description: 'Updated AWS Infrastructure for tláo.com redirect to GitHub Pages'

Parameters:
  DomainName:
    Type: String
    Default: 'xn--tlo-fla.com'
    Description: 'The Punycode domain name for the redirect'
  TargetDomain:
    Type: String
    Default: 'lstech-solutions.github.io'
    Description: 'The target domain to redirect to'
  TargetPath:
    Type: String
    Default: '/aws-tlao/'
    Description: 'The path to append to the target domain'
  CertificateArn:
    Type: String
    Description: 'ACM Certificate ARN for the domain (must be in us-east-1)'
    Default: ''

Resources:
  # S3 Bucket for Redirect - ALLOW public access for website
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'tlao-redirect-${AWS::AccountId}-final'
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref TargetDomain
          Protocol: https
      # ALLOW public access for website hosting
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      # Add bucket policy to allow public read access for website
      AccessControl: PublicRead

  # S3 Bucket Policy to allow public access for website
  RedirectBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RedirectBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${RedirectBucket.Arn}/*'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Redirect ${DomainName} to ${TargetDomain}${TargetPath}'
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        Origins:
          - Id: S3Redirect
            DomainName: !GetAtt RedirectBucket.RegionalDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Redirect
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # Route 53 A record pointing to CloudFront
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  # Route 53 CNAME record for www subdomain
  WWWDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub 'www.${DomainName}'
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Ref DomainName

Outputs:
  BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref RedirectBucket

  DistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution

  DistributionDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontURL:
    Description: 'CloudFront URL for testing'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'

  DomainURL:
    Description: 'Domain URL after DNS propagation'
    Value: !Sub 'https://${DomainName}'

  Instructions:
    Description: 'Deployment Complete'
    Value: !Sub |
      AWS Infrastructure deployed successfully!

      S3 bucket configured for public website access.
      CloudFront distribution updated.

      Next steps:
      1. Wait for CloudFront deployment (15-30 minutes)
      2. Test the redirect: https://${CloudFrontDistribution.DomainName}
      3. After DNS propagation: https://${DomainName}
      4. The domain will redirect to: https://${TargetDomain}${TargetPath}
