AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Infrastructure for tláo.com redirect to GitHub Pages'

Parameters:
  DomainName:
    Type: String
    Default: 'tláo.com'
    Description: 'The custom domain name for the redirect'
  TargetDomain:
    Type: String
    Default: 'lstech-solutions.github.io'
    Description: 'The target domain to redirect to'
  TargetPath:
    Type: String
    Default: '/aws-tlao/'
    Description: 'The path to append to the target domain'
  CertificateArn:
    Type: String
    Description: 'ACM Certificate ARN for the domain (must be in us-east-1)'
    Default: ''

Resources:
  # S3 Bucket for Redirect
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref TargetDomain
          Protocol: https
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # S3 Bucket Policy (for CloudFront access)
  RedirectBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RedirectBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub '${RedirectBucket.Arn}/*'

  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${DomainName} redirect'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Redirect ${DomainName} to ${TargetDomain}${TargetPath}'
        Aliases:
          - !Ref DomainName
          - !Sub 'www.${DomainName}'
        DefaultRootObject: index.html
        Origins:
          - Id: !Ref RedirectBucket
            DomainName: !Sub '${RedirectBucket}.s3-website-${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: !Ref RedirectBucket
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6' # Managed CachingOptimized
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SSLSupportMethod: sni-only

  # Route 53 Record Sets
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Sub 'www.${DomainName}'
          Type: CNAME
          TTL: 300
          SetIdentifier: www
          Weight: 100
          ResourceRecords:
            - !Ref DomainName

Outputs:
  BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref RedirectBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  DistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  DistributionDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomainName'
