AWSTemplateFormatVersion: '2010-09-09'
Description: 'Redirect tlao.com to GitHub Pages'

Parameters:
  DomainName:
    Type: String
    Default: tlao.com
    Description: The domain to redirect'

  TargetUrl:
    Type: String
    Default: https://lstech-solutions.github.io/aws-tlao/
    Description: The target URL for redirects'

Resources:
  # S3 Bucket for redirect website
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DomainName}'
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub '${TargetUrl#//}'
          Protocol: https

  # CloudFront Distribution for redirect
  RedirectCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub '${DomainName}.s3-website-${AWS::Region}.amazonaws.com'
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Headers:
              - Origin
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        HttpVersion: http2
        IsIPV6Enabled: true

  # ACM Certificate for the domain
  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName}'
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub '${DomainName}'

  # Route53 Record for redirect
  RedirectRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub '${DomainName}.'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt RedirectCloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

  # Route53 Record for www redirect
  WwwRedirectRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub 'www.${DomainName}.'
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt RedirectCloudFrontDistribution.DomainName
        EvaluateTargetHealth: false
